### ISSUE TITLE
Bug "Bulgarian as variant visible even if there is no variant"

### ISSUE THREAD

**Issue by cwurditsch** [Flowpack/Flowpack.NodeVariantSelector#5] opened 2019-10-17 09:59 UTC
The NodeVariantSelector is used in multi-sites instance with a central content hub. For structural reasons a meta language dimension "Global" is used. This meta language dimension is only visible for editors with administration rights. Other editors cannot see meta language dimension neither in the language menu nor in the  NodeVariantSelector

Currently the editors without administration rights see a node variant in the language dimension Bulgarian, even if there is no variant in this language dimension. This seems to be a problem due to the fact that Global is no visible for editors. 

There are two screenshots attached of the same page: (A) user Christian Wurditsch with admin rights (B) user Christian Test without admin rights
<img width="1111" alt="A - user Christian Wurditsch with admin rights" src="https://user-images.githubusercontent.com/31848464/66998569-c4fa9400-f0d4-11e9-9583-93ab898b18e8.png">
<img width="1122" alt="B - user Christian Test without admin rights" src="https://user-images.githubusercontent.com/31848464/66998580-c9bf4800-f0d4-11e9-8d15-2592b2dc5d4f.png">

```
Neos:
  ContentRepository:    
    contentDimensions:
      language:
        label: 'Language'
        icon: 'icon-language'
        # the default language dimension, if a new site is created
        default: all
        defaultPreset: all
        presets:
          bg:
            label: Bulgarian
            values:
              - bg
              - all
            uriSegment: bg
          sq:
            label: Albanien
            values:
              - sq
              - all
            uriSegment: sq
          all:
            label: Global
            values:
              - all
            uriSegment: all`
```

**Comment by dimaip** [comment] 2019-10-18 08:18
Thanks for the detailed report!
If there are any PRs to fix this I'll try to find the time to review them.

**Comment by dimaip** [comment] 2019-11-22 22:03
I've helped to debug this issue, and it seems to have been caused by AOPing into dimension handling, so closing it here.

**Closed by dimaip** 2019-11-22 22:03 UTC
